### ISSUE TITLE
downgrade forced for critical packages CSV and DataFrames

### ISSUE THREAD

**Issue by jonjilla** [sylvaticus/OdsIO.jl#3]
When adding package OdsIO, several packages are downgraded.    Here is the message in the REPL after running Pkg.add("OdsIO")

INFO: Downgrading CSV: v0.2.0 => v0.1.5
INFO: Downgrading CategoricalArrays: v0.3.3 => v0.1.6
INFO: Downgrading DataFrames: v0.11.3 => v0.10.1
INFO: Downgrading DataStreams: v0.3.4 => v0.1.3
INFO: Downgrading WeakRefStrings: v0.4.0 => v0.2.0

**Comment by sylvaticus** [comment]
Hello, I did verified and effectively the package makes other package to downgrade.
That's odd, as I did specified in the `require` file only lower bounds (or so it should according to the [require file format specifications](https://docs.julialang.org/en/stable/manual/packages/#Requirements-Specification-1)).
I will investigate it more.
In the meantime you can change the OdsIO `require` to
```
julia 0.5
PyCall 1.7
DataFrames 0.11.3
DataStructures 0.7.4
```
and run `Pkg.resolve()`:
```
julia> Pkg.resolve()
INFO: Upgrading CSV: v0.1.5 => v0.2.0
INFO: Upgrading CategoricalArrays: v0.1.6 => v0.3.3
INFO: Installing CodecZlib v0.4.2
INFO: Upgrading DataFrames: v0.10.1 => v0.11.3
INFO: Upgrading DataStreams: v0.1.3 => v0.3.4
INFO: Installing Missings v0.2.4
INFO: Installing NamedTuples v4.0.0
INFO: Installing TranscodingStreams v0.4.1
INFO: Upgrading WeakRefStrings: v0.2.0 => v0.4.1
INFO: Removing DataArrays v0.6.2
INFO: Removing FileIO v0.6.1
INFO: Removing GZip v0.3.0
INFO: Removing NullableArrays v0.1.2
INFO: Building SpecialFunctions
```
I will let you know when I will have found the reason of the downgrade.

**Comment by jonjilla** [comment]
I'm getting an error with DataStructures 0.7.4.  I used 0.7.3 and it seems to work.

**Comment by jonjilla** [comment]
After making these changes, it looks like I'm getting a new error which is likely due to the new NA handling in the new DataFrames package.

ERROR: UndefVarError: NA not defined

**Comment by sylvaticus** [comment]
Hello, for the reason behind the package downgrade you can read [this discussion](https://discourse.julialang.org/t/why-mypackage-is-forcing-other-package-downgrade-with-an-unbounded-require/8229).
For the NA issue, you can manually change `NA` with `missing` on the row 359 of file OdsIO.jl:
`s = join([join([(m[i,j]==nothing?missing:m[i,j]) for j in indices(m, 2)], '\t') for i in indices(m, 1)], '\n')`
With this change the package works, but some automatic conversions that were implemented still don't work with the newer version of DataFrame. I will try to sort them as well before making a release, so for the time being you can just use the package with that manual fix.

**Comment by sylvaticus** [comment]
Hello, I updated the package to use the new missing type of the latest DataFrames package.
I submitted the new release to be merged in the Julia package ecosystem, i.e. the new release should be available in a few hours with just a `Pkg.update()` .
