### ISSUE TITLE
Writing to specific sheets?

### ISSUE THREAD

**Issue by galaxite** [sylvaticus/OdsIO.jl#5]
I was reading the documentation for `ods_write()` in the readme, and I didn't see an option to write a dataset to a specific sheet name or index within an already existing ods file. Is this something that's possible with the package as it currently exists?

**Comment by sylvaticus** [comment]
yes, there should be possible. Just give me 5 minutes to write you an example...

**Comment by sylvaticus** [comment]
Ods file, before: 
![image](https://user-images.githubusercontent.com/2077159/44860669-1482c400-ac77-11e8-832f-06bf84b2c0ec.png)

```
using DataFrames, OdsIO
df = DataFrame(B=[20,200],C=[30,300])
ods_write("test.ods",Dict(("Sheet2",2,3)=>df))
```

Ods file, after:
![image](https://user-images.githubusercontent.com/2077159/44861027-f23d7600-ac77-11e8-9624-7267e5c06d9f.png)

You can specify the sheet by either name or position, and the top-left corner where to export the data as a tuple of `(row,column)` (sorry, I didn't implemented excel-like addresses as `A5`, just use `(1,5)` instead).

If you have other cells that compute a value from the exported cells, don't forget to use `CTRL+Shift+F9` to force a re-computation of the values.

**Comment by galaxite** [comment]
Thank you, that's exactly what I was looking for!
