### ISSUE TITLE
`ods_write` don't accept any `AbstractDict` that is not a `Dict`

### ISSUE THREAD

**Issue by jessymilare** [sylvaticus/OdsIO.jl#8]
There is a strange test at line 72:

```
    if ! isa(data,Dict)
        error("The data parameter must be a dictionary of location_where_to_export_the_data -> exported_data. Type `?ods_write` for more informations.")
    end
```

I got that error using a `SortedDict`. After commenting that, there was no problem for me.

Why doesn't the function accept `AbstractDict`s and why isn't that in the function type signature instead of a test in the middle of the code?

**Comment by sylvaticus** [comment]
Thank you. I think I was too rigid in the test. I'll look on it tomorrow.

**Comment by sylvaticus** [comment]
Thank you, I did commit the upgraded test for `AbstractDict`.

I can't recall why it is there. For now I left the test in the code as, for newcomers, return a more informative error than a "MethodError".
But I agree it is not the most clean solution.
